from TeamIndia import DEV_USERS, DRAGONS, DEMONS, TIGERS, CODERS, WOLVES, telethn

IMMUNE_USERS = DRAGONS + WOLVES + DEMONS + TIGERS + DEV_USERS + CODERS

IMMUNE_USERS = (
    list(DRAGONS) + list(WOLVES) + list(DEMONS) + list(TIGERS) + list(DEV_USERS) + list(CODERS) 
)
